<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MongoDB.Bson" Version="3.10.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.10.0" />
    <PackageReference Include="MongoDB.Driver.Core" Version="2.30.0" />
    <PackageReference Include="CloudinaryDotNet" Version="1.27.9" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataAcessLayer\DataAcessLayer.csproj" />
    <ProjectReference Include="..\EntityLayer\EntityLayer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Validations\" />
  </ItemGroup>

</Project>
